# Generated by Django 5.2.10 on 2026-01-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pv',
            name='meeting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pv',
            name='summary',
            field=models.TextField(blank=True, help_text='Short summary of the PV'),
        ),
    ]
