# Generated by Django 5.2.10 on 2026-01-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pv_meeting_date_pv_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='pv',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='pvs/docs/'),
        ),
        migrations.AlterField(
            model_name='pv',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pvs/images/'),
        ),
    ]
